version: "3.7"
services:
  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile-dispatcher
    environment:
      FLASK_ENV: development
      DISPATCHER_VECTORIZERS: '["http://vectorizer-1:8000","http://vectorizer-2:8000"]'
      DISPATCHER_PREDICTORS: '["http://predictor-1:8000","http://predictor-2:8000"]'
      DISPATCHER_MODELS: '{"combined":[1.0, 1.0], "fig":[1.0, 0], "letters":[0, 1.0]}'
    command: gunicorn --bind 0.0.0.0 --workers 2 --worker-tmp-dir /dev/shm --reload dispatcher.api:app
    ports:
      - 5000:8000
    volumes:
      - ./dispatcher:/dispatcher
  vectorizer-1:
    build:
      context: .
      dockerfile: Dockerfile-vectorizer
    environment:
      FLASK_ENV: development
      VECTORIZER_WIDTH: "2048"
      VECTORIZER_IDENTIFIER: fig_uspto_v1_18
      VECTORIZER_CONSTRUCTOR: obj:ViennaVectorizer('models/fig_uspto_v1_18.state', 1093)
    command: gunicorn --bind 0.0.0.0 --workers 2 --worker-tmp-dir /dev/shm --reload vectorizer.api:app
    ports:
      - 5001:8000
    volumes:
      - ./vectorizer:/vectorizer
  vectorizer-2:
    build:
      context: .
      dockerfile: Dockerfile-vectorizer
    environment:
      FLASK_ENV: development
      VECTORIZER_WIDTH: "2048"
      VECTORIZER_IDENTIFIER: fig_uspto_v2_34
      VECTORIZER_CONSTRUCTOR: obj:ViennaVectorizer('models/fig_v2_34.state', 2454)
    command: gunicorn --bind 0.0.0.0 --workers 2 --worker-tmp-dir /dev/shm --reload vectorizer.api:app
    ports:
      - 5002:8000
    volumes:
      - ./vectorizer:/vectorizer
  predictor-1:
    build:
      context: .
      dockerfile: Dockerfile-predictor
    environment:
      FLASK_ENV: development
      PREDICTOR_HEIGHT: "1000"
      PREDICTOR_TYPE: float32
    command: gunicorn --bind 0.0.0.0 --workers 2 --worker-tmp-dir /dev/shm --reload predictor.api:app
    ports:
      - 5003:8000
    volumes:
      - ./predictor:/predictor
  predictor-2:
    build:
      context: .
      dockerfile: Dockerfile-predictor
    environment:
      FLASK_ENV: development
      PREDICTOR_HEIGHT: "1000"
      PREDICTOR_TYPE: float32
    command: gunicorn --bind 0.0.0.0 --workers 2 --worker-tmp-dir /dev/shm --reload predictor.api:app
    ports:
      - 5004:8000
    volumes:
      - ./predictor:/predictor
            