version: "3"
services:
  dispatcher:
    build: dispatcher/
    environment:
      FLASK_ENV: development
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --worker-tmp-dir /dev/shm --reload api:app
    ports:
      - 5000:5000
    volumes:
      - ./dispatcher:/dispatcher
  vectorizer-1:
    build: vectorizer/
    environment:
      FLASK_ENV: development
      VECTORIZER_NAME: vectorizer 1
    command: gunicorn --bind 0.0.0.0:5001 --workers 2 --worker-tmp-dir /dev/shm --reload api:app
    ports:
      - 5001:5001
    volumes:
      - ./vectorizer:/vectorizer
  vectorizer-2:
    build: vectorizer/
    environment:
      FLASK_ENV: development
      VECTORIZER_NAME: vectorizer 2
    command: gunicorn --bind 0.0.0.0:5002 --workers 2 --worker-tmp-dir /dev/shm --reload api:app
    ports:
      - 5002:5002
    volumes:
      - ./vectorizer:/vectorizer
    